using Mutagen.Bethesda;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Synthesis;

namespace CoinPatcher;

public static class Program
{
    private static Lazy<Settings> _settings = null!;

    public static Task<int> Main(string[] args)
    {
        return SynthesisPipeline.Instance
            .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
            .SetAutogeneratedSettings("Settings", "settings.json", out _settings)
            .SetTypicalOpen(GameRelease.SkyrimSE, "CoinPatcher.esp")
            .Run(args);
    }

    public static void RunPatch(
        IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
    {
        CoinPatcher.Run(state, _settings.Value, Console.Out);
    }
}
